name: Caller workflow

on:
  workflow_dispatch:
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses : peter-evans/repository-dispatch
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          event-type: MyEvent
          client-payload: '{"paramA": "123"}'