name: schedule
on:
  schedule:
    - cron: '30 1-22/3 * * *'
    - cron: '0 0-21/3 * * *'

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Hello les mecs
      run: |
        echo Salut les gars